### ISSUE TITLE
No instructions how to run tests; no wdio.conf.js

### ISSUE THREAD

**Issue by thomergil** [pako88/wdio-mocha-typescript#2]
This all looks great, thank you for putting it together. But instructions are lacking. How do I run tests? I expected to see a wdio.conf.js file.

**Comment by thomergil** [comment]
Maybe it's `npm run test:chromedriver`, and other commands in `package.json`. It would be good to document that.

**Comment by pako88** [comment]
thanks, i will definitively do that!
wdio configuration is located in the config folder.
you can use the integrated debug scripts for visual studio code, or you can run the tests with `npm run test:chromedriver`.
i will add a description in the near future

**Comment by thomergil** [comment]
`npm run test:chromedriver` immediately leads to errors about chromedriver. It would be good if you documented the dependency on chromedriver and referred to installation instructions.

**Comment by pako88** [comment]
if you've done a `npm install` before, there shouldn't be any other dependency. (except of the current stable chrome version).
if there are still errors, please open another issue with these errors!

**Comment by thomergil** [comment]
Also, it's unclear what process transpiled the .ts config files into .js. I assume you ran `tsc` at some point, but I think it should be documented as part of a boilerplate project like this.

**Comment by pako88** [comment]
i will document this, too.
it's being transpiled on the fly with ts-node.
you can look at following file for example:  
https://github.com/pako88/wdio-mocha-typescript/blob/master/config/chromedriver.conf.js

**Comment by thomergil** [comment]
I understand, but then your repo should come without the .js files.

**Comment by thomergil** [comment]
Also, no errors during `npm install`.

```
$ npm install                                                                                                     <<<

> fibers@4.0.3 install /Users/thomer/tmp/nobackup/wdio-mocha-typescript/node_modules/fibers
> node build.js || nodejs build.js

  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/fibers.node
Installed in `/Users/thomer/tmp/nobackup/wdio-mocha-typescript/node_modules/fibers/bin/darwin-x64-83/fibers.node`

> chromedriver@83.0.1 install /Users/thomer/tmp/nobackup/wdio-mocha-typescript/node_modules/chromedriver
> node install.js

ChromeDriver binary exists. Validating...
ChromeDriver is already available at '/var/folders/q0/f4tncvcs2k7_v_skcsrsq78m0000gn/T/83.0.4103.39/chromedriver/chromedriver'.
Copying to target path /Users/thomer/tmp/nobackup/wdio-mocha-typescript/node_modules/chromedriver/lib/chromedriver
Fixing file permissions.
Done. ChromeDriver binary available at /Users/thomer/tmp/nobackup/wdio-mocha-typescript/node_modules/chromedriver/lib/chromedriver/chromedriver

> core-js@3.6.5 postinstall /Users/thomer/tmp/nobackup/wdio-mocha-typescript/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> ejs@3.1.3 postinstall /Users/thomer/tmp/nobackup/wdio-mocha-typescript/node_modules/ejs
> node --harmony ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

added 892 packages from 573 contributors and audited 892 packages in 15.891s

54 packages are looking for funding
  run `npm fund` for details

found 14 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by thomergil** [comment]
Wait, wait, wait. Now that I do it again, it works. Weird! I apologize, I must have done something wrong before. Closing this issue, though my comment about additional documentation stands.

**Comment by thomergil** [comment]
I realize now that the `.js` files you included are wrappers around the `.ts` files.

**Comment by pako88** [comment]
i added the documentation to the readme.  
feel free to reopen this issue if somethings missing from your point of view.
