### ISSUE TITLE
No showing any typescript error and just showing passed on the console.

### ISSUE THREAD

**Issue by poc7667** [pako88/wdio-mocha-typescript#6]
I did have typescript error on my source code.
```
[0-0] PASSED in chrome - /test/specs/basic/01_new_apartments.spec.ts

Spec Files:	 1 passed, 1 total (100% completed) in 00:00:06
```

    it('should take screenshot',() => {
        browser.thisIsACrapButButStillShowingSuccess()?????
    });

Any idea?

**Comment by pako88** [comment]
i updated the packages and now it is showing correctly an error.
